server:
  port: 8889

spring:
  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 1qaz2wsx
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  # redis配置 url队列存储如果不使用redis，可以不配置
#  redis:
#    host: localhost
#    port: 6379
#    password: test

crawler:
  # url队列存储方式 file、mysql或者redis 不配置则使用file
  url-queue-storage-type: file
  # 文件拓展名
  file-extensions: 'txt,csv,doc,docx,pdf,odt,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,bmp,mp3,wav,mp4,avi,zip'
  # url队列文件路径
  url-file-path: /root/myapp/simple-search-engine/data
  base:
    thread-count: 1
    web-list:
      - https://www.e-iceblue.cn/
      - https://www.qdnzmg.cn/