server:
  port: 8889

spring:
  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    hikari:
      minimum-idle: 6
      maximum-pool-size: 10
      connection-timeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

crawler:
  # 文件拓展名
  file-extensions: 'txt,csv,doc,docx,pdf,odt,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,bmp,mp3,wav,mp4,avi,zip'
  base:
    thread-count: 5
    web-list:
      - https://www.e-iceblue.cn/
      - https://www.sougou.com/

  queue:
    max-size: 1000