server:
  port: 8888

spring:
  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/search_engine
    username: root
    password: 1qaz2wsx

crawler:
  # 文件拓展名
  file-extensions: 'txt,csv,doc,docx,pdf,odt,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,bmp,mp3,wav,mp4,avi,zip'
  base:
    thread-count: 12
    web-list:
      - https://www.qdnzmg.cn/