server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/search_engine
    username: root
    password: root

crawler:
  base:
    thread-count: 3
    web-list:
      - https://www.sogou.com/
      - https://www.tsinghua.edu.cn/